services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8080:8080"  # Expose the application on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev

