services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - backend_deps:/root/.m2  # Volume for Maven dependencies
    ports:
      - "8080:8080"  # Expose the application on port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      volumes:
        - ./frontend:/frontend
        - /frontend/node_modules
      ports:
        - "3000:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true

volumes:
  backend_deps: